version = 3.8.3
runner.dialect = scala3

maxColumn = 100
align.preset = more
align.openParenCallSite = false

assumeStandardLibraryStripMargin = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors,
  Imports
]

rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["java\\..*", "javax\\..*", "jakarta\\..*"],
  ["scala\\..*"],
  [".*"],
  ["se\\.citerus\\..*"]
]

newlines.afterCurlyLambdaParams = squash
newlines.implicitParamListModifierPrefer = before

docstrings.style = Asterisk
docstrings.wrap = no
