package se.citerus.dddsample.domain.model.cargo

import java.util.Objects

/** Uniquely identifies a particular cargo. Automatically generated by the
  * application.
  *
  * Modelled as a Scala 3 opaque type — a zero-cost wrapper over `String` that
  * disappears at runtime but is distinct from `String` at compile time.
  */
opaque type TrackingId = String

object TrackingId:

  def apply(id: String): TrackingId =
    Objects.requireNonNull(id, "Tracking id must not be null")
    require(id.nonEmpty, "Tracking id must not be empty")
    id

  extension (t: TrackingId)
    def idString: String                       = t
    def sameValueAs(other: TrackingId): Boolean = t == other
